[pytest]


# Pytest Execution Settings

addopts =
    -v
    --tb=short
    --alluredir=allure-results
    --strict-markers


# Test Discovery

testpaths = tests

python_files = test_*.py
python_classes = Test*
python_functions = test_*


# Custom Markers

markers =
    smoke: Smoke tests
    regression: Regression tests
    sanity: Sanity tests
    ui: UI tests
    api: API tests
    e2e: End-to-end tests
    security: Security validation tests
    delete: Tests related to delete functionality
    negative: marks negative test scenarios
    


# Console Logging

log_cli = true
log_cli_level = INFO


# Warnings

filterwarnings =
    ignore::DeprecationWarning