[pytest]

addopts = -v --tb=short

markers =
    smoke: Smoke tests
    regression: Regression tests
    sanity: Sanity tests
    ui: UI tests
    api: API tests
    e2e: End-to-end tests
    security: Security validation tests
    delete: Tests related to delete functionality

testpaths = tests